baseurl = "https://blackjjw.github.io/"
title = "Black_JJW's Blog"
languageCode = "en-us"
paginate = "10" # Number of posts per page
paginatePath = "page"
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-65FHK1SBF9" # Enable Google Analytics by entering your tracking id

[Author]
  name = "JUNG JIN WOO"
  bio = ""
  avatar = ""

[Params]
  description = "JUNG JIN WOO's Blog for programming" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.style.vars]
  highlightColor = "#e22d30"

[Params.logo]
  subtitle = "Create, Read, Update, Delete" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  github = "blackJJW"
  email = "jjinwoo92@gmail.com"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "python"
    name = "Python"
    url = "/categories/python/"
    weight = 2
  [[menu.main]]
    identifier = "java"
    name = "Java"
    url = "/categories/Java/"
    weight = 3
  [[menu.main]]
    identifier = "html"
    name = "HTML"
    url = "/categories/HTML/"
    weight = 4
  [[menu.main]]
    identifier = "javascript"
    name = "JavaScript"
    url = "/categories/javascript/"
    weight = 5
  [[menu.main]]
    identifier = "algorithm"
    name = "Algorithm"
    url = "/categories/algorithm/"
    weight = 6
  [[menu.main]]
    identifier = "SQL"
    name = "sql"
    url = "/categories/sql/"
    weight = 7
  [[menu.main]]
    identifier = "ml"
    name = "ML"
    url = "/categories/ml/"
    weight = 8
  [[menu.main]]
    identifier = "dl"
    name = "DL"
    url = "/categories/dl/"
    weight = 9
  [[menu.main]]
    identifier = "Statistics"
    name = "statistics"
    url = "/categories/statistics/"
    weight = 10
  [[menu.main]]
    identifier = "setting"
    name = "Setting"
    url = "/categories/setting/"
    weight = 11
  [[menu.main]]
    identifier = "linux"
    name = "Linux"
    url = "/categories/Linux/"
    weight = 12
  [[menu.main]]
    identifier = "bash"
    name = "Bash"
    url = "/categories/bash/"
    weight = 13
  [[menu.main]]
    [[menu.main]]
    identifier = "computer system"
    name = "computer system"
    url = "/categories/computer-system/"
    weight = 14
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/categories/projects/"
    weight = 15
  